view:
  site:
    wxPayEnable: ${wx.pay.enable}
    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
    needPayArticleReadCount: 20 # 付费文章，未付费可以看到的文章内容
    websiteName: TechVerse
    websiteLogoUrl: https://paicoding.com/img/icon.png
    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
    zsxqUrl: https://paicoding.com/article/detail/314
    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
    contactMeTitle: 联系我 - 一个热爱技术的研究生
    contactMeWxQrCode: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png
    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 苏ICP备2025162487号
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到vauni的TechVerse网站，请与他人进行积极的交流吧～
    oss: