image:
  abs-tmp-path: /tmp/storage/
  web-img-path: /forum/image/
  tmp-upload-path: /tmp/forum/
  cdn-host:
  oss:
    type: ali
    prefix: paicoding/
    endpoint: oss-cn-beijing.aliyuncs.com
    ak:
    sk:
    bucket: devcoding
    host: https://devcoding.oss-cn-beijing.aliyuncs.com/

spring:
  web:
    resources:
      # 支持本地图片上传之后的链接，其中 file:///d的用于win系统，后面的file: 适用于mac/linux系统
      static-locations:
        - classpath:/static/
        - file:///d:${image.abs-tmp-path}
        - file:${image.abs-tmp-path}

